# Generated by Django 3.1.4 on 2021-07-01 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0004_auto_20210630_0136'),
        ('playlist', '0002_auto_20210701_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='tracks',
            field=models.ManyToManyField(blank=True, to='artist.Track'),
        ),
    ]
