# Generated by Django 3.1.4 on 2021-07-02 00:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0005_auto_20210701_2125'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('playlist', '0003_auto_20210701_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Proprietário(a)'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='tracks',
            field=models.ManyToManyField(blank=True, to='artist.Track', verbose_name='Músicas'),
        ),
    ]
