# Generated by Django 3.1.4 on 2021-06-30 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='tracks',
            field=models.ManyToManyField(related_name='tracks', to='artist.Track', verbose_name='Músicas'),
        ),
    ]
