# Generated by Django 3.1.4 on 2021-06-30 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0003_remove_album_tracks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='album',
        ),
        migrations.AlterField(
            model_name='artist',
            name='genre',
            field=models.CharField(choices=[('AXE', 'Axé'), ('PAG', 'Pagode'), ('SAM', 'Samba'), ('SER', 'Sertanejo'), ('FOR', 'Forró'), ('POP', 'Pop'), ('ROC', 'Metal'), ('MET', 'Metal'), ('FUN', 'Funk'), ('REG', 'Reggae'), ('ERU', 'Erudito'), ('RAP', 'Rap'), ('MPB', 'Mpb'), ('ARR', 'Arrocha')], max_length=3, verbose_name='Gênero'),
        ),
        migrations.DeleteModel(
            name='Album',
        ),
    ]
