# Generated by Django 3.1.4 on 2021-07-02 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0004_auto_20210630_0136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='genre',
            field=models.CharField(choices=[('AXE', 'Axé'), ('PAG', 'Pagode'), ('SAM', 'Samba'), ('SER', 'Sertanejo'), ('FOR', 'Forró'), ('POP', 'Pop'), ('ROC', 'Metal'), ('MET', 'Metal'), ('FUN', 'Funk'), ('REG', 'Reggae'), ('ERU', 'Erudito'), ('RAP', 'Rap'), ('MPB', 'Mpb'), ('ARR', 'Arrocha'), ('INS', 'Instrumental')], max_length=3, verbose_name='Gênero'),
        ),
    ]
